name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
trigger: none
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
      os: windows # allowed values: windows, linux, or macOS. The default value is windows.
    featureFlags:
      disableNetworkIsolation: true
    stages:
      - stage: Stage
        jobs:
          - job: Build_and_Sign
            displayName: Build and Sign Plugin
            timeoutInMinutes: 360
            templateContext:
              mb:
                signing:
                  enabled: true
                  signType: real
                  signWithProd: true
                  zipSources: false
                  useEsrpCli: true
                  feedSource: 'https://mseng.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
              outputs:
                - output: pipelineArtifact
                  artifactName: drop
                  targetPath: $(build.artifactstagingdirectory)/drop
                  displayName: "Publish Artifact: drop"
            steps:
              - checkout: self
                clean: true
                fetchTags: false
              - task: PowerShell@2
                displayName: Install JDK 17
                inputs:
                  targetType: inline
                  script: |
                    # Download Adoptium/Temurin JDK 17.0.12
                    Write-Host "Downloading Java 17.0.12..."
                    $source = "https://download.oracle.com/java/17/archive/jdk-17.0.12_windows-x64_bin.zip"
                    $destination = "$(build.sourcesdirectory)\jdk17_x64_windows.zip"
                    Invoke-WebRequest -Uri $source -OutFile $destination
              - task: JavaToolInstaller@0
                displayName: 'Use Java 17'
                inputs:
                  versionSpec: 17
                  jdkArchitectureOption: x64
                  jdkSourceOption: LocalDirectory
                  jdkFile: '$(build.sourcesdirectory)\jdk17_x64_windows.zip'
                  jdkDestinationDirectory: '$(agent.toolsDirectory)/jdk17'
              - task: PowerShell@2
                displayName: Build Plugin
                inputs:
                  targetType: inline
                  script: |
                    mvn -v
                    # ./gradlew buildUtils || exit -1
                    mvn clean install -f ./Utils/pom.xml -T 1C "-Dcheckstyle.skip=true" "-Dmaven.test.skip=true" "-Dmaven.javadoc.skip=true"
                    mvn clean -f ./Utils/pom.xml
                    cd PluginsAndFeatures/azure-toolkit-for-intellij
                    ./gradlew clean buildPlugin -s "-Papplicationinsights.key=$(INTELLIJ_KEY)" "-PneedPatchVersion=false" "-Psources=false" "-Porg.gradle.configureondemand=false" "-Porg.gradle.daemon=false" "-Porg.gradle.unsafe.configuration-cache=false" "-Porg.gradle.caching=false"
              - task: PowerShell@2
                displayName: Unpackage
                inputs:
                  targetType: inline
                  script: |
                    New-Item -ItemType Directory -Path ".\artifacts\intellij\" -Force
                    $zipFile = Get-ChildItem ".\PluginsAndFeatures\azure-toolkit-for-intellij\build\distributions\*.zip" | Select-Object -First 1
                    Copy-Item $zipFile.FullName ".\artifacts\intellij\azure-toolkit-for-intellij.zip"
                    Expand-Archive -Path ".\artifacts\intellij\azure-toolkit-for-intellij.zip" -DestinationPath ".\artifacts\intellij\folder" -Force
                    Remove-Item ".\artifacts\intellij\azure-toolkit-for-intellij.zip"
              - task: PowerShell@2
                displayName: Sign jars
                timeoutInMinutes: 240
                inputs:
                  targetType: inline
                  script: |
                    $ABSOLUTE_PATH = Get-Location
                    # Generate the signing-filelist.xml file
                    '<?xml version="1.0" encoding="utf-8" ?>' | Out-File -FilePath signing-filelist.xml -Encoding utf8
                    '<filelist>' | Out-File -FilePath signing-filelist.xml -Append -Encoding utf8
                    '    <certificate certnumbers="100010171">' | Out-File -FilePath signing-filelist.xml -Append -Encoding utf8
                    
                    Get-ChildItem -Path . -Recurse -File | Where-Object { 
                        $_.Name -like "azure-intellij-*.jar" -or 
                        $_.Name -like "azure-toolkit-for-intellij*.jar" -or 
                        $_.Name -like "azure-toolkit-ide-*.jar" -or 
                        $_.Name -like "azuretools-core-*.jar" -or 
                        $_.Name -like "azure-explorer-common-*.jar" -or 
                        $_.Name -like "hdinsight-node-common-*.jar" -or 
                        $_.Name -eq "azure-sdk-reference-book.jar" 
                    } | ForEach-Object {
                        $abs_path = $_.FullName
                        "        <file srcpath=`"$abs_path`" dstpath=`"$abs_path`"></file>" | Out-File -FilePath signing-filelist.xml -Append -Encoding utf8
                    }
                    
                    '    </certificate>' | Out-File -FilePath signing-filelist.xml -Append -Encoding utf8
                    '</filelist>' | Out-File -FilePath signing-filelist.xml -Append -Encoding utf8
                    
                    dotnet "$env:MBSIGN_APPFOLDER/DDSignFiles.dll" -- /filelist:signing-filelist.xml
                    Remove-Item signing-filelist.xml                    
                  workingDirectory: 'artifacts/intellij/folder'
              - task: CmdLine@2
                displayName: Repackage
                inputs:
                  script: |
                    echo Starting repackaging...
                    cd artifacts\intellij\folder
                    echo Removing log files...
                    del /s /q *.log
                    echo Creating final zip archive: azure-toolkit-for-intellij-$(Build.BuildNumber).zip
                    tar -a -c -f ..\..\azure-toolkit-for-intellij-$(Build.BuildNumber).zip *
                    echo Repackaging completed successfully
              - task: CopyFiles@2
                displayName: "Copy Files to: $(build.artifactstagingdirectory)"
                inputs:
                  SourceFolder: $(system.defaultworkingdirectory)/artifacts
                  Contents: "*.zip"
                  TargetFolder: $(build.artifactstagingdirectory)/drop
              - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
                displayName: "Manifest Generator "
                inputs:
                  BuildDropPath: $(build.artifactstagingdirectory)/drop